### ISSUE TITLE
Tabs: hovered tab looks the same as selected tab

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/react-components#38]
<img width="484" alt="f84c9906-bc62-11e6-9c91-f62d7d84443c" src="https://cloud.githubusercontent.com/assets/114976/20983889/27c66eb8-bc8c-11e6-8626-4bb74ee0e81e.png">

Filed on internal tracker: https://github.ibm.com/Watson/developer-experience/issues/1385

**Comment by jzhang300** [comment]
The design has changed slightly since this issue.
